#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/src-tauri/resources/deno-runtime"
RUNTIME_BIN_DIR="$RUNTIME_DIR/bin"

cleanup_stale_target_resources() {
  local candidate=""
  for candidate in \
    "$ROOT_DIR/src-tauri/target/debug/resources/deno-runtime" \
    "$ROOT_DIR/src-tauri/target/release/resources/deno-runtime" \
    "$ROOT_DIR/src-tauri/target/release/bundle/macos/PineFetch.app/Contents/Resources/resources/deno-runtime"
  do
    if [[ -e "$candidate" ]]; then
      chmod -R u+rwX "$candidate" 2>/dev/null || true
      rm -rf "$candidate"
    fi
  done
}

DENO_BIN="${PINEFETCH_DENO_BIN:-}"

if [[ -z "$DENO_BIN" ]]; then
  if command -v deno >/dev/null 2>&1; then
    DENO_BIN="$(command -v deno)"
  fi
fi

if [[ -z "$DENO_BIN" ]]; then
  echo "deno not found. Install deno or set PINEFETCH_DENO_BIN."
  exit 1
fi

if [[ ! -x "$DENO_BIN" ]]; then
  echo "Configured deno binary is not executable."
  exit 1
fi

mkdir -p "$ROOT_DIR/src-tauri/resources"
rm -rf "$RUNTIME_DIR"
mkdir -p "$RUNTIME_BIN_DIR"
cleanup_stale_target_resources

cp "$DENO_BIN" "$RUNTIME_BIN_DIR/deno"
chmod 755 "$RUNTIME_BIN_DIR/deno"

DENO_VERSION="$("$RUNTIME_BIN_DIR/deno" --version | head -n1 | sed 's/^deno //')"

cat > "$RUNTIME_DIR/.pinefetch-deno-runtime" <<META
deno=$DENO_VERSION
source_deno=$DENO_BIN
META

cat > "$RUNTIME_DIR/.keep" <<'META'
placeholder for source control
META

cat > "$RUNTIME_DIR/PLACEHOLDER" <<'META'
This file keeps the deno-runtime resource path present in source control.
The runtime is generated by scripts/prepare-deno-runtime.sh during build.
META

echo "Bundled deno runtime ready at: $RUNTIME_DIR"
echo "deno: $DENO_VERSION"
