$ErrorActionPreference = "Stop"

$RootDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$ResourcesDir = Join-Path $RootDir "src-tauri\resources"
$FfmpegRuntimeDir = Join-Path $ResourcesDir "ffmpeg-runtime"
$FfmpegRuntimeBinDir = Join-Path $FfmpegRuntimeDir "bin"
$DenoRuntimeDir = Join-Path $ResourcesDir "deno-runtime"
$DenoRuntimeBinDir = Join-Path $DenoRuntimeDir "bin"
$WhisperRuntimeDir = Join-Path $ResourcesDir "whisper-runtime"

function Resolve-ToolPath {
    param(
        [string]$EnvValue,
        [string[]]$Candidates,
        [string]$Label
    )

    if ($EnvValue -and $EnvValue.Trim()) {
        $resolved = Resolve-Path $EnvValue.Trim()
        return $resolved.Path
    }

    foreach ($candidate in $Candidates) {
        $command = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($command) {
            return $command.Source
        }
    }

    throw "$Label not found. Install it or set the matching PINEFETCH_* environment variable."
}

function Reset-Directory {
    param([string]$Path)

    if (Test-Path $Path) {
        Remove-Item -Recurse -Force $Path
    }
    New-Item -ItemType Directory -Force $Path | Out-Null
}

function Invoke-Checked {
    param(
        [string]$FilePath,
        [string[]]$Arguments,
        [string]$Label
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$Label failed with exit code $LASTEXITCODE."
    }
}

function Remove-StaleResourceCopies {
    $candidates = @(
        "src-tauri\target\debug\resources",
        "src-tauri\target\release\resources",
        "src-tauri\target\x86_64-pc-windows-msvc\debug\resources",
        "src-tauri\target\x86_64-pc-windows-msvc\release\resources"
    )

    foreach ($candidate in $candidates) {
        $path = Join-Path $RootDir $candidate
        if (Test-Path $path) {
            Remove-Item -Recurse -Force $path
        }
    }
}

function Assert-PythonVersion {
    param([string]$PythonPath)

    Invoke-Checked `
        -FilePath $PythonPath `
        -Arguments @("-c", "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)") `
        -Label "Python version check"
}

New-Item -ItemType Directory -Force $ResourcesDir | Out-Null
Remove-StaleResourceCopies

$ffmpegBin = Resolve-ToolPath `
    -EnvValue $env:PINEFETCH_FFMPEG_BIN `
    -Candidates @("ffmpeg.exe", "ffmpeg") `
    -Label "ffmpeg"
$ffprobeBin = Resolve-ToolPath `
    -EnvValue $env:PINEFETCH_FFPROBE_BIN `
    -Candidates @("ffprobe.exe", "ffprobe") `
    -Label "ffprobe"

Reset-Directory $FfmpegRuntimeDir
New-Item -ItemType Directory -Force $FfmpegRuntimeBinDir | Out-Null
Copy-Item $ffmpegBin (Join-Path $FfmpegRuntimeBinDir "ffmpeg.exe") -Force
Copy-Item $ffprobeBin (Join-Path $FfmpegRuntimeBinDir "ffprobe.exe") -Force

$ffmpegVersion = (& (Join-Path $FfmpegRuntimeBinDir "ffmpeg.exe") -version | Select-Object -First 1) -replace "^ffmpeg version ", ""
$ffprobeVersion = (& (Join-Path $FfmpegRuntimeBinDir "ffprobe.exe") -version | Select-Object -First 1) -replace "^ffprobe version ", ""
@"
ffmpeg=$ffmpegVersion
ffprobe=$ffprobeVersion
source_ffmpeg=$ffmpegBin
source_ffprobe=$ffprobeBin
"@ | Set-Content -Encoding UTF8 (Join-Path $FfmpegRuntimeDir ".pinefetch-ffmpeg-runtime")
"placeholder for source control" | Set-Content -Encoding UTF8 (Join-Path $FfmpegRuntimeDir ".keep")
"The runtime is generated by scripts/prepare-windows-runtime.ps1 during Windows builds." |
    Set-Content -Encoding UTF8 (Join-Path $FfmpegRuntimeDir "PLACEHOLDER")

$denoBin = Resolve-ToolPath `
    -EnvValue $env:PINEFETCH_DENO_BIN `
    -Candidates @("deno.exe", "deno") `
    -Label "deno"

Reset-Directory $DenoRuntimeDir
New-Item -ItemType Directory -Force $DenoRuntimeBinDir | Out-Null
Copy-Item $denoBin (Join-Path $DenoRuntimeBinDir "deno.exe") -Force

$denoVersion = (& (Join-Path $DenoRuntimeBinDir "deno.exe") --version | Select-Object -First 1) -replace "^deno ", ""
@"
deno=$denoVersion
source_deno=$denoBin
"@ | Set-Content -Encoding UTF8 (Join-Path $DenoRuntimeDir ".pinefetch-deno-runtime")
"placeholder for source control" | Set-Content -Encoding UTF8 (Join-Path $DenoRuntimeDir ".keep")
"The runtime is generated by scripts/prepare-windows-runtime.ps1 during Windows builds." |
    Set-Content -Encoding UTF8 (Join-Path $DenoRuntimeDir "PLACEHOLDER")

$pythonBin = Resolve-ToolPath `
    -EnvValue $env:PINEFETCH_WHISPER_PYTHON_BIN `
    -Candidates @("python.exe", "python", "python3") `
    -Label "Python 3.10+"
Assert-PythonVersion $pythonBin

Reset-Directory $WhisperRuntimeDir
Write-Host "Creating bundled whisper runtime using: $pythonBin"
Invoke-Checked `
    -FilePath $pythonBin `
    -Arguments @("-m", "venv", $WhisperRuntimeDir) `
    -Label "Python venv creation"

$runtimePython = Join-Path $WhisperRuntimeDir "Scripts\python.exe"
Invoke-Checked `
    -FilePath $runtimePython `
    -Arguments @("-m", "pip", "install", "--upgrade", "pip") `
    -Label "pip upgrade"
Invoke-Checked `
    -FilePath $runtimePython `
    -Arguments @("-m", "pip", "install", "--upgrade", "faster-whisper") `
    -Label "faster-whisper install"

$fasterWhisperVersion = & $runtimePython -c "import faster_whisper; print(faster_whisper.__version__)"
$runtimePythonVersion = & $runtimePython -c "import sys; print(sys.version.split()[0])"
@"
faster-whisper=$fasterWhisperVersion
python=$runtimePythonVersion
"@ | Set-Content -Encoding UTF8 (Join-Path $WhisperRuntimeDir ".pinefetch-whisper-runtime")
"placeholder for source control" | Set-Content -Encoding UTF8 (Join-Path $WhisperRuntimeDir ".keep")
"The runtime is generated by scripts/prepare-windows-runtime.ps1 during Windows builds." |
    Set-Content -Encoding UTF8 (Join-Path $WhisperRuntimeDir "PLACEHOLDER")

Write-Host "Windows ffmpeg runtime ready at: $FfmpegRuntimeDir"
Write-Host "ffmpeg: $ffmpegVersion"
Write-Host "ffprobe: $ffprobeVersion"
Write-Host "Windows deno runtime ready at: $DenoRuntimeDir"
Write-Host "deno: $denoVersion"
Write-Host "Windows whisper runtime ready at: $WhisperRuntimeDir"
Write-Host "faster-whisper: $fasterWhisperVersion"
