#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/src-tauri/resources/whisper-runtime"

if [[ "${OSTYPE:-}" == msys* || "${OSTYPE:-}" == cygwin* || "${OSTYPE:-}" == win32* ]]; then
  echo "Windows runtime bundling via this script is not supported yet."
  exit 1
fi

PYTHON_BIN="${PINEFETCH_WHISPER_PYTHON_BIN:-}"
if [[ -z "$PYTHON_BIN" ]]; then
  for candidate in python3.12 python3.11 python3.10; do
    if command -v "$candidate" >/dev/null 2>&1; then
      PYTHON_BIN="$(command -v "$candidate")"
      break
    fi
  done
fi

if [[ -z "$PYTHON_BIN" ]]; then
  echo "No compatible Python executable found (expected python3.10+)."
  exit 1
fi

mkdir -p "$ROOT_DIR/src-tauri/resources"
rm -rf "$RUNTIME_DIR"

echo "Creating bundled whisper runtime using: $PYTHON_BIN"
"$PYTHON_BIN" -m venv "$RUNTIME_DIR"

"$RUNTIME_DIR/bin/python" -m pip install --upgrade pip
"$RUNTIME_DIR/bin/python" -m pip install --upgrade faster-whisper

RUNTIME_VERSION="$($RUNTIME_DIR/bin/python - <<'PY'
import faster_whisper
print(faster_whisper.__version__)
PY
)"

RUNTIME_PYTHON="$($RUNTIME_DIR/bin/python - <<'PY'
import sys
print(sys.version.split()[0])
PY
)"

cat > "$RUNTIME_DIR/.pinefetch-whisper-runtime" <<META
faster-whisper=$RUNTIME_VERSION
python=$RUNTIME_PYTHON
META

cat > "$RUNTIME_DIR/.keep" <<'META'
placeholder for source control
META

cat > "$RUNTIME_DIR/PLACEHOLDER" <<'META'
This file keeps the whisper-runtime resource path present in source control.
The runtime is generated by scripts/prepare-whisper-runtime.sh during build.
META

echo "Bundled runtime ready at: $RUNTIME_DIR"
echo "faster-whisper version: $RUNTIME_VERSION"
