#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/src-tauri/resources/ffmpeg-runtime"
RUNTIME_BIN_DIR="$RUNTIME_DIR/bin"

cleanup_stale_target_resources() {
  local candidate=""
  for candidate in \
    "$ROOT_DIR/src-tauri/target/debug/resources/ffmpeg-runtime" \
    "$ROOT_DIR/src-tauri/target/release/resources/ffmpeg-runtime" \
    "$ROOT_DIR/src-tauri/target/release/bundle/macos/PineFetch.app/Contents/Resources/resources/ffmpeg-runtime"
  do
    if [[ -e "$candidate" ]]; then
      chmod -R u+rwX "$candidate" 2>/dev/null || true
      rm -rf "$candidate"
    fi
  done
}

FFMPEG_BIN="${PINEFETCH_FFMPEG_BIN:-}"
FFPROBE_BIN="${PINEFETCH_FFPROBE_BIN:-}"

if [[ -z "$FFMPEG_BIN" ]]; then
  if command -v ffmpeg >/dev/null 2>&1; then
    FFMPEG_BIN="$(command -v ffmpeg)"
  fi
fi

if [[ -z "$FFPROBE_BIN" ]]; then
  if command -v ffprobe >/dev/null 2>&1; then
    FFPROBE_BIN="$(command -v ffprobe)"
  fi
fi

if [[ -z "$FFMPEG_BIN" || -z "$FFPROBE_BIN" ]]; then
  echo "ffmpeg/ffprobe not found. Install them or set PINEFETCH_FFMPEG_BIN and PINEFETCH_FFPROBE_BIN."
  exit 1
fi

if [[ ! -x "$FFMPEG_BIN" || ! -x "$FFPROBE_BIN" ]]; then
  echo "Configured ffmpeg/ffprobe binaries are not executable."
  exit 1
fi

mkdir -p "$ROOT_DIR/src-tauri/resources"
rm -rf "$RUNTIME_DIR"
mkdir -p "$RUNTIME_BIN_DIR"
cleanup_stale_target_resources

cp "$FFMPEG_BIN" "$RUNTIME_BIN_DIR/ffmpeg"
cp "$FFPROBE_BIN" "$RUNTIME_BIN_DIR/ffprobe"
chmod 755 "$RUNTIME_BIN_DIR/ffmpeg" "$RUNTIME_BIN_DIR/ffprobe"

FFMPEG_VERSION="$("$RUNTIME_BIN_DIR/ffmpeg" -version | head -n1 | sed 's/^ffmpeg version //')"
FFPROBE_VERSION="$("$RUNTIME_BIN_DIR/ffprobe" -version | head -n1 | sed 's/^ffprobe version //')"

cat > "$RUNTIME_DIR/.pinefetch-ffmpeg-runtime" <<META
ffmpeg=$FFMPEG_VERSION
ffprobe=$FFPROBE_VERSION
source_ffmpeg=$FFMPEG_BIN
source_ffprobe=$FFPROBE_BIN
META

cat > "$RUNTIME_DIR/.keep" <<'META'
placeholder for source control
META

cat > "$RUNTIME_DIR/PLACEHOLDER" <<'META'
This file keeps the ffmpeg-runtime resource path present in source control.
The runtime is generated by scripts/prepare-ffmpeg-runtime.sh during build.
META

echo "Bundled ffmpeg runtime ready at: $RUNTIME_DIR"
echo "ffmpeg: $FFMPEG_VERSION"
echo "ffprobe: $FFPROBE_VERSION"
